pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS  = credentials('github-token')
        NEXUS_DOCKER_CRED   = credentials('nexus-docker-credentials')
        NEXUS_DOCKER_REPO   = 'localhost:5000/docker-hosted'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', credentialsId: 'github-token', url: 'https://github.com/SelimRiahi/test-jenk.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('test') {
                        // Build and tag the image with the Nexus repository URL
                        bat 'docker build -t %NEXUS_DOCKER_REPO%/static-api:latest .'
                    }
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    bat 'docker run -d -p 3000:3000 --name static-api %NEXUS_DOCKER_REPO%/static-api:latest'
                }
            }
        }

        stage('Push Docker Image to Nexus') {
            steps {
                script {
                    // Login to Nexus Docker registry
                    bat 'docker login %NEXUS_DOCKER_REPO% -u %NEXUS_DOCKER_CRED_USR% -p %NEXUS_DOCKER_CRED_PSW%'
                    // Push image to Nexus
                    bat 'docker push %NEXUS_DOCKER_REPO%/static-api:latest'
                }
            }
        }
    }
}

